<script>
	import { Content, Grid, Row, Column, Breadcrumb, BreadcrumbItem } from 'carbon-components-svelte';

	import CrudTable from '$lib/components/CrudTable.svelte';
	import BaseDetailModal from '$lib/components/detailModals/BaseDetailModal.svelte';
	import getCrudService from '$lib/services/CrudService';
	import MinuteField from '$lib/fields/MinuteField';

	// Converts a time entry instance to a representation that can be displayed in the table.
	// Converts the minutes field to a time string in the format HH:MM
	// and converts ids for related worker and task to links
	const toRepresentation = (instance) => {
		return {
			...instance,
			time: MinuteField.toRepresentation(instance.minutes),
			workerLink: {
				value: instance._workerTitle,
				link: `/app/workers/?id=${instance.Worker}`,
				type: 'link'
			},
			taskLink: {
				value: instance._taskName,
				link: `/app/tasks/?id=${instance.Task}`,
				type: 'link'
			}
		};
	};

	let resourcePath = '/quote_builder/time_entry';

	// Arguments for detailModal
	let detailModalConfig = {
		type: 'Time Entry',
		identityField: 'name',
		// Converts a time entry instance to a representation that can be displayed in the modal
		toRepresentation: (instance) => {
			return {
				...instance,
				minutes: MinuteField.toRepresentation(instance.minutes)
			};
		},
		// Converts a time entry instance from the modal representation provided by the user to a
		// representation that can be sent to the backend
		toInternalValue: (instance) => {
			return { ...instance, minutes: MinuteField.toInternalValue(instance.minutes) };
		},
		// Field definitions for the modal.
		fields: [
			{
				key: 'Worker',
				title: 'Worker',
				type: 'dropdown',
				required: true,
				// Dropdown fields use crud services to fetch items to be selected in the dropdown
				items: {
					service: getCrudService('/quote_builder/worker'),
					keyField: 'title'
				}
			},
			{
				key: 'Task',
				title: 'Task',
				type: 'dropdown',
				required: true,
				items: {
					service: getCrudService('/quote_builder/task'),
					keyField: 'name'
				}
			},
			{
				key: 'minutes',
				title: 'Time',
				type: 'time',
				required: true
			}
		],
		resourcePath
	};

	// Headers for the table
	// header keys are used to pull values from the table representation generated by toRepresentation, above
	let crudTableHeaders = [
		{
			key: 'workerLink',
			value: 'Worker'
		},
		{
			key: 'taskLink',
			value: 'Task',
			_link: true
		},
		{
			key: 'time',
			value: 'Time (HH:MM)'
		},
		{
			key: 'overflow',
			empty: true
		}
	];
</script>

<Content>
	<Grid fullWidth style="padding: 0;">
		<Row class="row-header">
			<Column>
				<Breadcrumb noTrailingSlash aria-label="Page navigation">
					<BreadcrumbItem href="/app">Dashboard</BreadcrumbItem>
					<BreadcrumbItem href="/app/tasks">Time Entries</BreadcrumbItem>
				</Breadcrumb>
			</Column>
		</Row>

		<CrudTable
			{resourcePath}
			headers={crudTableHeaders}
			title="Time Entries"
			{detailModalConfig}
			DetailModal={BaseDetailModal}
			{toRepresentation}
		/>
	</Grid>
</Content>

<style>
	:global(.row-header) {
		margin-bottom: 'spacing-03';
	}
</style>
