# Only for me locally
cm4025:
  hosts: 13.42.171.46
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /home/main/.ssh/aws-personal.pem
    ansible_ssh_common_args: "-o IdentitiesOnly=yes"
