name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Frontend Docker
      run: docker build ./frontend --file frontend/Dockerfile --tag test:latest

    - name: Build backend Docker
      run: docker build ./frontend --file frontend/Dockerfile --tag test:latest
